version: 2.1

executors:
  linux:
    docker:
      - image: circleci/golang:1.16
  macos:
    macos:
      xcode: 11.4

defaults: &defaults
  docker:
    - image: circleci/golang:1.16
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - build:
          matrix:
            parameters:
              platform: [linux, macos]
              arch: ["amd64","arm64"]
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make test
  build:
    parameters:
      platform:
        type: executor
      arch:
        type: string
    executor: << parameters.platform >>
    environment:
      - GOOS: << parameters.platform >>
      - GOARCH: << parameters.arch >>
    <<: *defaults
    steps:
      - checkout
      # Compile, and make sure it's not dynamically linked.
      - run: make bin/ssm-env && ! ldd bin/ssm-env
      - store_artifacts:
          path: bin/ssm-env
          destination: ssm-env-<< parameters.platform >>-<< parameters.arch >>
